version: '3.7'

services:
    lockkliye_webapp:
        build:
            context: .
            dockerfile: Dockerfile.prod
            network: host
        command: nginx -g "daemon off;"
        container_name: lockkliye_webapp
        env_file: .env
        environment:
            - NODE_ENV=production
            - GENERATE_SOURCEMAP=false
        networks:
            - lockkliye_local
        ports:
            - 443:443
        volumes:
            - '.:/lockkliye_webapp'

networks:
    lockkliye_local:
        name: lockkliye_local
        driver: bridge
        external: true
